services:
  - type: web
    name: ai-trip-planner-backend
    runtime: python
    buildCommand: pip install -r requirement.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: GPLACES_API_KEY
        sync: false
      - key: OPENWEATHERMAP_API_KEY
        sync: false
      - key: EXCHANGE_RATE_API_KEY
        sync: false
      - key: LANGCHAIN_API_KEY
        sync: false